### ISSUE TITLE
Feature request: Rotate AWS ECR Docker images

### ISSUE THREAD

**Issue by ivan-pinatti** [cloudposse/jenkins#8]
Hi,

It would be nice to rotate images stored in AWS ECR in order to save storage consumption. IMHO, a good number to keep would be 7.

Two possible solutions:

1. Add an extra step in the **post_build** after [Docker push](https://github.com/cloudposse/jenkins/blob/master/buildspec.yml#L19) to delete images
2. Add AWS ECR lifecycle policy -[https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html](https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html)

Cheers!

**Comment by aknysh** [comment]
@ivan-pinatti 
this is a very good point
let us review it

**Comment by osterman** [comment]
This is a great idea! Thanks for the contribution.

**Comment by ivan-pinatti** [comment]
@osterman @aknysh,

These 3 PRs will solve this issue;

- [https://github.com/cloudposse/terraform-aws-codebuild/pull/13](https://github.com/cloudposse/terraform-aws-codebuild/pull/13)
- [https://github.com/cloudposse/jenkins/pull/9](https://github.com/cloudposse/jenkins/pull/9)
- [https://github.com/cloudposse/terraform-aws-ecr/pull/7](https://github.com/cloudposse/terraform-aws-ecr/pull/7)

**Comment by aknysh** [comment]
@ivan-pinatti 
we merged all three PRs above.
Also released a new version of https://github.com/cloudposse/terraform-aws-jenkins/releases/tag/0.3.6
that uses all the new features.
thanks for the help.
will close this for now
